service: flight-service-monitor

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: eu-west-3
  timeout: 30

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get
